import topPickupsData from './topPickups.json';
import suggestionsData from './suggestions.json';

export interface LocationDetail {
  address: string;
  lat: number;
  lon: number;
}

export interface LocationSuggestions {
  commonPickups: string[];
  conditionalDropoffs: Record<string, string[]>;
  locations: Record<string, LocationDetail>;
}

/** IAW Courier location autocomplete and conditional dropoff routing data. */
export const locationSuggestions = suggestionsData as LocationSuggestions;

/** CSV-derived top pickup shortcuts (regenerated by backend seed). */
export const TOP_PICKUPS: string[] =
  (topPickupsData as { topPickups: string[] }).topPickups ?? [];

/** @deprecated Use TOP_PICKUPS from archive stats */
export const POPULAR_PICKUPS = TOP_PICKUPS.length > 0 ? TOP_PICKUPS : [
  'Mobile Parts Inc.',
  'Wajax',
  'Sandvik Mining',
  'Onaping Depth Project (ODP)',
  'Komatsu (260)',
  'Epiroc Lively',
];

/**
 * Returns dropoff suggestions for a selected pickup location.
 */
export function dropoffsForPickup(pickupName: string): string[] {
  if (!pickupName) return locationSuggestions.commonPickups;
  return (
    locationSuggestions.conditionalDropoffs[pickupName] ??
    locationSuggestions.commonPickups.filter((name) => name !== pickupName)
  );
}

/**
 * Returns the seeded address for a known business location, if available.
 */
export function addressForLocation(name: string): string {
  return locationSuggestions.locations[name]?.address ?? '';
}

/**
 * Returns lat/lon for a known business location when available.
 */
export function coordsForLocation(name: string): { lat?: number; lon?: number } {
  const loc = locationSuggestions.locations[name];
  if (!loc) return {};
  return { lat: loc.lat, lon: loc.lon };
}
