import topPickupsData from './topPickups.json';
import baselineSuggestions from './suggestions.json';

export interface LocationDetail {
  address: string;
  lat: number;
  lon: number;
}

export interface LocationSuggestions {
  commonPickups: string[];
  conditionalDropoffs: Record<string, string[]>;
  locations: Record<string, LocationDetail>;
}

/** Active suggestions — baseline until hydrateLocationSuggestions() loads archive data. */
export let locationSuggestions: LocationSuggestions = baselineSuggestions as LocationSuggestions;

/** CSV-derived top pickup shortcuts (regenerated by backend seed). */
export const TOP_PICKUPS: string[] =
  (topPickupsData as { topPickups: string[] }).topPickups ?? [];

/** @deprecated Use TOP_PICKUPS from archive stats */
export const POPULAR_PICKUPS = TOP_PICKUPS.length > 0 ? TOP_PICKUPS : [
  'Acme Warehouse',
  'Beta Supply Co.',
  'Gamma Depot',
];

/**
 * Fetches archive-derived suggestions written by backend seed (gitignored).
 * Falls back to committed synthetic baseline when the file is absent.
 */
export async function hydrateLocationSuggestions(): Promise<void> {
  try {
    const res = await fetch('/data/suggestions.generated.json', { cache: 'no-store' });
    if (!res.ok) return;

    const data = (await res.json()) as LocationSuggestions;
    if (Array.isArray(data.commonPickups) && data.commonPickups.length > 0) {
      locationSuggestions = data;
    }
  } catch {
    // Offline or fresh clone — keep synthetic baseline.
  }
}

/**
 * Returns dropoff suggestions for a selected pickup location.
 */
export function dropoffsForPickup(pickupName: string): string[] {
  if (!pickupName) return locationSuggestions.commonPickups;
  return (
    locationSuggestions.conditionalDropoffs[pickupName] ??
    locationSuggestions.commonPickups.filter((name) => name !== pickupName)
  );
}

/**
 * Returns the seeded address for a known business location, if available.
 */
export function addressForLocation(name: string): string {
  return locationSuggestions.locations[name]?.address ?? '';
}

/**
 * Returns lat/lon for a known business location when available.
 */
export function coordsForLocation(name: string): { lat?: number; lon?: number } {
  const loc = locationSuggestions.locations[name];
  if (!loc) return {};
  return { lat: loc.lat, lon: loc.lon };
}
